# Generated by Django 5.0 on 2023-12-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='enable_json_ld_script',
        ),
    ]
