# Generated by Django 5.0 on 2023-12-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_enable_json_ld_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='enable_json_ld_script',
        ),
    ]
