# Generated by Django 5.0 on 2024-01-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='json_ld_script',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_robot_follow',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_robot_index',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
