# Generated by Django 4.2.7 on 2024-03-20 21:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctor", "0005_alter_chamber_doctor"),
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DocotorAppointment",
            new_name="DoctorAppointment",
        ),
        migrations.AlterUniqueTogether(
            name="doctorappointment",
            unique_together={("user", "doctor", "chamber", "date", "time")},
        ),
    ]
