# Generated by Django 4.2.7 on 2024-03-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0005_alter_chamber_doctor"),
        ("appointment", "0002_rename_docotorappointment_doctorappointment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorappointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"profile": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctor.doctor",
            ),
        ),
    ]
