# Generated by Django 4.2.7 on 2024-05-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0007_doctorappointment_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("cancel", "Cancelled"),
                    ("done", "Done"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="testappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("cancel", "Cancelled"),
                    ("done", "Done"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
