# Generated by Django 4.2.7 on 2024-03-04 20:46

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chamber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "availability",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "profile_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        max_length=1500,
                        null=True,
                        quality=100,
                        scale=None,
                        size=[1920, 1080],
                        upload_to="Doctor_Profile/",
                    ),
                ),
                (
                    "experience_year",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("license_no", models.CharField(blank=True, max_length=100, null=True)),
                ("slug", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("general", "General"),
                            ("superadmin", "Super Admin"),
                            ("doctor", "Doctor"),
                            ("hospital", "hospital"),
                        ],
                        default="doctor",
                        max_length=50,
                    ),
                ),
                ("address", models.TextField(blank=True, max_length=500)),
                ("phone_number", models.CharField(max_length=50, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.unions",
                    ),
                ),
                (
                    "specialists",
                    models.ManyToManyField(blank=True, to="app.specialist"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "working_place",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="doctor.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="doctor.doctor",
                    ),
                ),
            ],
        ),
    ]
