# Generated by Django 4.2.7 on 2024-06-20 13:04

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(blank=True, max_length=500, null=True)),
                ('fee_bn', models.CharField(blank=True, max_length=500, null=True)),
                ('availability', models.CharField(blank=True, max_length=500, null=True)),
                ('availability_bn', models.CharField(blank=True, max_length=500, null=True)),
                ('personal', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('address_bn', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Prof. Dr.', 'Prof. Dr.'), ('Assoc. Prof. Dr.', 'Assoc. Prof. Dr.'), ('Asst. Prof. Dr.', 'Asst. Prof. Dr.'), ('Consultant', 'Consultant')], default='Dr.', max_length=20)),
                ('qualification', models.CharField(blank=True, max_length=500, null=True)),
                ('qualification_bn', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, max_length=1500, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='Doctor_Profile/')),
                ('experience_year', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_year_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('license_no_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('nid', models.CharField(blank=True, max_length=100, null=True)),
                ('nid_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('slug_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('general', 'General'), ('superadmin', 'Super Admin'), ('doctor', 'Doctor'), ('hospital', 'Hospital'), ('ambulance', 'Ambulance')], default='doctor', max_length=50)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('address_bn', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True)),
                ('profile', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=500, null=True)),
                ('service_name_bn', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=500, null=True)),
                ('designation_bn', models.CharField(blank=True, max_length=500, null=True)),
                ('working_place', models.CharField(blank=True, max_length=500, null=True)),
                ('working_place_bn', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('content', models.TextField(blank=True, max_length=1500, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_review', to='doctor.doctor')),
            ],
        ),
    ]
