# Generated by Django 4.2.7 on 2024-02-21 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0002_remove_doctor_designation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chamber",
            name="address",
        ),
    ]
