# Generated by Django 4.2.7 on 2024-03-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="profile",
            field=models.BooleanField(default=False),
        ),
    ]
