# Generated by Django 5.0 on 2024-02-08 19:18

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_specialist'),
        ('doctor', '0003_alter_doctor_specialists'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chamber',
            name='hospital',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.unions'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, max_length=1500, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='Doctor_Profile/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('general', 'General'), ('superadmin', 'Super Admin'), ('doctor', 'Doctor'), ('hospital', 'hospital')], default='doctor', max_length=50),
        ),
    ]
