# Generated by Django 4.0 on 2024-06-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
        ('doctor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialists',
            field=models.ManyToManyField(blank=True, to='app.Specialist'),
        ),
    ]
