# Generated by Django 4.2.7 on 2024-02-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0003_remove_chamber_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
