# Generated by Django 4.2.7 on 2024-03-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0003_doctor_email_doctor_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamber",
            name="address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="chamber",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="chamber",
            name="personal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("general", "General"),
                    ("superadmin", "Super Admin"),
                    ("doctor", "Doctor"),
                    ("hospital", "Hospital"),
                ],
                default="doctor",
                max_length=50,
            ),
        ),
    ]
