# Generated by Django 5.0 on 2024-02-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_chamber_address_chamber_hospital_doctor_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='experience',
            new_name='experience_year',
        ),
    ]
