# Generated by Django 4.2.7 on 2024-03-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0004_chamber_address_chamber_name_chamber_personal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamber",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chambers",
                to="doctor.doctor",
            ),
        ),
    ]
