# Generated by Django 4.2.7 on 2024-02-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0004_doctor_email_doctor_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
