# Generated by Django 4.2.7 on 2024-02-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0006_remove_doctor_specialists_doctor_specialists"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="specialists",
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialists",
            field=models.ManyToManyField(blank=True, to="doctor.specialist"),
        ),
    ]
