# Generated by Django 4.2.7 on 2024-04-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0007_alter_chamber_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="nid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="title",
            field=models.CharField(
                choices=[
                    ("Dr.", "Dr."),
                    ("Prof. Dr.", "Prof. Dr."),
                    ("Assoc. Prof. Dr.", "Assoc. Prof. Dr."),
                    ("Asst. Prof. Dr.", "Asst. Prof. Dr."),
                    ("Consultant", "Consultant"),
                ],
                default="Dr.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="doctorservice",
            name="bn_service_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
