# Generated by Django 4.2.7 on 2024-04-09 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0008_doctor_nid_doctor_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorservice",
            name="bn_service_name",
        ),
    ]
