# Generated by Django 4.2.7 on 2024-04-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0009_remove_doctorservice_bn_service_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorservice",
            name="doctor",
        ),
        migrations.AddField(
            model_name="doctor",
            name="services",
            field=models.ManyToManyField(blank=True, to="doctor.doctorservice"),
        ),
    ]
