# Generated by Django 4.2.7 on 2024-05-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0010_remove_doctorservice_doctor_doctor_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamber",
            name="address_bn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="chamber",
            name="availability_bn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="chamber",
            name="fee_bn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="chamber",
            name="name_bn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="address_bn",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="doctor",
            name="experience_year_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="license_no_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="name_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="nid_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="qualification_bn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="slug_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="doctorservice",
            name="service_name_bn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="designation_bn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="working_place_bn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
