# Generated by Django 4.2.7 on 2024-05-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0012_doctor_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chamber",
            old_name="fee",
            new_name="new_patient_fee",
        ),
        migrations.RenameField(
            model_name="chamber",
            old_name="fee_bn",
            new_name="new_patient_fee_bn",
        ),
        migrations.AddField(
            model_name="chamber",
            name="old_patientfee",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="chamber",
            name="old_patientfee_bn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
