# Generated by Django 4.2.7 on 2024-05-07 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0013_rename_fee_chamber_new_patient_fee_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chamber",
            old_name="new_patient_fee",
            new_name="fee",
        ),
        migrations.RenameField(
            model_name="chamber",
            old_name="new_patient_fee_bn",
            new_name="fee_bn",
        ),
        migrations.RemoveField(
            model_name="chamber",
            name="old_patientfee",
        ),
        migrations.RemoveField(
            model_name="chamber",
            name="old_patientfee_bn",
        ),
    ]
