# Generated by Django 4.2.7 on 2024-05-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_rename_new_patient_fee_chamber_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
