# Generated by Django 4.2.7 on 2024-05-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0016_alter_ambulance_location_alter_hospital_location"),
        ("doctor", "0017_alter_doctor_location"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="review",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospital_review",
                to="hospital.hospital",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_review",
                to="doctor.doctor",
            ),
        ),
        migrations.RemoveField(
            model_name="review",
            name="appointment",
        ),
    ]
