# Generated by Django 4.2.7 on 2024-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0018_alter_review_unique_together_review_hospital_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
