# Generated by Django 4.2.7 on 2024-06-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0019_alter_review_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
