# Generated by Django 4.2.7 on 2024-06-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_districts_district_name_bn_and_more"),
        ("doctor", "0021_alter_doctor_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="services",
        ),
        migrations.AddField(
            model_name="doctorservice",
            name="specialist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_specialist",
                to="app.specialist",
            ),
        ),
    ]
