# Generated by Django 4.2.7 on 2024-06-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_districts_district_name_bn_and_more"),
        ("doctor", "0023_alter_doctorservice_specialist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorservice",
            name="specialist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialist",
                to="app.specialist",
            ),
        ),
    ]
