# Generated by Django 4.2.7 on 2024-03-04 20:46

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Districts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district_name", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Divisions",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("division_name", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("service_description", models.TextField(blank=True, null=True)),
                (
                    "service_logo",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        max_length=1500,
                        null=True,
                        quality=100,
                        scale=None,
                        size=[1920, 1080],
                        upload_to="services_logo/",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialist_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("specialist_description", models.TextField(blank=True, null=True)),
                (
                    "specialist_logo",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        max_length=1500,
                        null=True,
                        quality=100,
                        scale=None,
                        size=[1920, 1080],
                        upload_to="specialist_logo/",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Upazilas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upazila_name", models.CharField(blank=True, max_length=50)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.districts"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("union_name", models.CharField(blank=True, max_length=50)),
                (
                    "upazila",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.upazilas"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="districts",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.divisions"
            ),
        ),
    ]
