# Generated by Django 5.0 on 2023-12-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('user', '0007_alter_profile_blood_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blood',
        ),
    ]
