# Generated by Django 4.2.7 on 2024-02-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="service_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
