# Generated by Django 4.2.7 on 2024-04-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="service_description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="services",
            name="service_name_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="services",
            name="slug_bn",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
