# Generated by Django 4.2.7 on 2024-02-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_services_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="service_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
