# Generated by Django 5.0 on 2024-01-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_divisions_remove_district_division_and_more'),
        ('user', '0008_remove_profile_district_remove_profile_division_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
