# Generated by Django 4.2.7 on 2024-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_services_service_description_bn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="slug_bn",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="specialist",
            name="specialist_description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specialist",
            name="specialist_name_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
