# Generated by Django 4.2.7 on 2024-02-22 00:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_specialist_service_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specialist",
            old_name="service_description",
            new_name="specialist_description",
        ),
    ]
