# Generated by Django 4.2.7 on 2024-02-23 14:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_service_description_specialist_specialist_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="service_logo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                max_length=1500,
                null=True,
                quality=100,
                scale=None,
                size=[1920, 1080],
                upload_to="services_logo/",
            ),
        ),
    ]
