# Generated by Django 4.2.7 on 2024-05-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_specialist_slug_bn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="designation_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="name_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="short_text_bn",
            field=models.TextField(blank=True, null=True),
        ),
    ]
