# Generated by Django 5.0 on 2024-01-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_district_delete_division_delete_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
