# Generated by Django 4.2.7 on 2024-02-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_services_service_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="specialist",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
