# Generated by Django 5.0 on 2024-01-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_districts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Unions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_name', models.CharField(blank=True, max_length=50)),
                ('upazila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.upazilas')),
            ],
        ),
        migrations.DeleteModel(
            name='PostOffice',
        ),
    ]
