# Generated by Django 5.0 on 2024-01-24 11:11

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_description', models.CharField(blank=True, max_length=250, null=True)),
                ('service_logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, max_length=1500, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='specialist_logo/')),
            ],
        ),
    ]
