# Generated by Django 5.0 on 2024-02-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialist',
        ),
    ]
