# Generated by Django 4.2.7 on 2024-05-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="link",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
