# Generated by Django 4.2.7 on 2024-05-12 19:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_goal_otherscontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="icon",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                max_length=1500,
                null=True,
                quality=100,
                scale=None,
                size=[1920, 1080],
                upload_to="goal_icon/",
            ),
        ),
    ]
