# Generated by Django 4.2.7 on 2024-05-17 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_remove_unions_upazila"),
        ("doctor", "0017_alter_doctor_location"),
        ("hospital", "0016_alter_ambulance_location_alter_hospital_location"),
        ("user", "0004_alter_profile_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Unions",
        ),
    ]
