# Generated by Django 4.2.7 on 2024-05-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_sitesettings_mail_sitesettings_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_ques", models.CharField(blank=True, max_length=200, null=True)),
                ("f_ques_bn", models.CharField(blank=True, max_length=200, null=True)),
                ("f_and", models.CharField(blank=True, max_length=200, null=True)),
                ("f_and_bn", models.CharField(blank=True, max_length=200, null=True)),
                ("position", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
