# Generated by Django 4.2.7 on 2024-06-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="districts",
            name="district_name_bn",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="divisions",
            name="division_name_bn",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="upazilas",
            name="upazila_name_bn",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
