# Generated by Django 4.2.7 on 2024-02-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="donor",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_donate_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
