# Generated by Django 4.2.7 on 2024-02-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_profile_donor_profile_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="donor",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
