# Generated by Django 5.0 on 2023-12-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_superuser',
        ),
    ]
