# Generated by Django 5.0 on 2023-12-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('general', 'General'), ('superadmin', 'Super Admin')], default='general', max_length=50),
        ),
    ]
