# Generated by Django 5.0 on 2023-12-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_postal_code_profile_blood_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Postal_Code',
            new_name='postal_code',
        ),
    ]
