# Generated by Django 4.2.7 on 2024-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_profile_blood_group_alter_profile_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("general", "General"),
                    ("superadmin", "Super Admin"),
                    ("doctor", "Doctor"),
                    ("hospital", "Hospital"),
                    ("ambulance", "Ambulance"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
