# Generated by Django 5.0 on 2024-02-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('general', 'General'), ('superadmin', 'Super Admin'), ('doctor', 'Doctor'), ('hospital', 'hospital')], default='general', max_length=50),
        ),
    ]
