# Generated by Django 4.2.7 on 2024-06-20 13:04

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('address_bn', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('slug_bn', models.SlugField(blank=True, null=True, unique=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('profile', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=500, null=True)),
                ('service_name_bn', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_name_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('fee', models.CharField(blank=True, max_length=200, null=True)),
                ('fee_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_time_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('slug_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.testcatagory')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_no', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_no_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('address_bn', models.TextField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=500, null=True)),
                ('availability_bn', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('diagnostic_center', 'Diagnostic Center')], max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('general', 'General'), ('superadmin', 'Super Admin'), ('doctor', 'Doctor'), ('hospital', 'Hospital'), ('ambulance', 'Ambulance')], default='hospital', max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('slug_bn', models.SlugField(blank=True, null=True, unique=True)),
                ('hospital_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, max_length=1500, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='hospital/')),
                ('website', models.URLField(blank=True, null=True)),
                ('profile', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.upazilas')),
                ('services', models.ManyToManyField(blank=True, to='hospital.hospitalservice')),
                ('specialists', models.ManyToManyField(blank=True, to='app.specialist')),
                ('tests', models.ManyToManyField(blank=True, to='hospital.test')),
            ],
        ),
    ]
