# Generated by Django 4.2.7 on 2024-03-04 20:46

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, max_length=500)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "availability",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hospital", "Hospital"),
                            ("clinic", "Clinic"),
                            ("diagnostic_center", "Diagnostic Center"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("longitude", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("general", "General"),
                            ("superadmin", "Super Admin"),
                            ("doctor", "Doctor"),
                            ("hospital", "hospital"),
                        ],
                        default="hospital",
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "hospital_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        max_length=1500,
                        null=True,
                        quality=100,
                        scale=None,
                        size=[1920, 1080],
                        upload_to="hospital/",
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.unions",
                    ),
                ),
                ("services", models.ManyToManyField(blank=True, to="app.services")),
                (
                    "specialists",
                    models.ManyToManyField(blank=True, to="app.specialist"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ambulance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("ac", models.BooleanField(default=False)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address", models.TextField(blank=True, max_length=500)),
                ("slug", models.SlugField(unique=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.hospital",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.unions",
                    ),
                ),
            ],
        ),
    ]
