# Generated by Django 5.0 on 2024-01-08 16:30

import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_blood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, max_length=1500, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='hospital/')),
                ('facilities', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('specialties', models.TextField(blank=True, null=True)),
                ('accreditation_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('is_emergency_services_available', models.BooleanField(default=False)),
                ('is_pharmacy_available', models.BooleanField(default=False)),
                ('is_ambulance_available', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.division')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
