# Generated by Django 4.2.7 on 2024-02-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="ac",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hospital",
            name="ambulance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hospital",
            name="ambulance_phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
