# Generated by Django 4.2.7 on 2024-06-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='slug_bn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
