# Generated by Django 5.0 on 2024-01-03 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_blood'),
        ('hospital', '0002_remove_hospital_contact_information_hospital_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.district'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.division'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.state'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
    ]
