# Generated by Django 4.2.7 on 2024-02-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_hospital_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hospital", "Hospital"),
                    ("clinic", "Clinic"),
                    ("diagnostic_center", "Diagnostic Center"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
