# Generated by Django 4.2.7 on 2024-03-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_hospital_profile_hospital_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("general", "General"),
                    ("superadmin", "Super Admin"),
                    ("doctor", "Doctor"),
                    ("hospital", "Hospital"),
                ],
                default="hospital",
                max_length=50,
            ),
        ),
    ]
