# Generated by Django 5.0 on 2024-01-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospital_district_hospital_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
