# Generated by Django 4.0 on 2024-06-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
        ('hospital', '0003_alter_hospital_slug_alter_hospital_slug_bn'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='services',
            field=models.ManyToManyField(blank=True, to='hospital.HospitalService'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='specialists',
            field=models.ManyToManyField(blank=True, to='app.Specialist'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='tests',
            field=models.ManyToManyField(blank=True, to='hospital.Test'),
        ),
    ]
