# Generated by Django 4.2.7 on 2024-03-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0004_alter_hospital_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCatagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(blank=True, max_length=200, null=True)),
                ("price", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "delivery_time",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("slug", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "catagory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.testcatagory",
                    ),
                ),
            ],
        ),
    ]
