# Generated by Django 5.0 on 2024-01-03 20:47

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_hospital_accreditation_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, max_length=1500, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='hospital/'),
        ),
    ]
