# Generated by Django 4.2.7 on 2024-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0005_testcatagory_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="tests",
            field=models.ManyToManyField(blank=True, to="hospital.test"),
        ),
    ]
