# Generated by Django 4.2.7 on 2024-04-25 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0007_rename_price_test_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="services",
        ),
        migrations.CreateModel(
            name="HospitalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="hospital.hospital",
                    ),
                ),
            ],
        ),
    ]
