# Generated by Django 5.0 on 2024-01-06 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_hospital_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='accreditation_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='facilities',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
