# Generated by Django 4.2.7 on 2024-04-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0008_remove_hospital_services_hospitalservice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospitalservice",
            name="hospital",
        ),
        migrations.AddField(
            model_name="hospital",
            name="services",
            field=models.ManyToManyField(blank=True, to="hospital.hospitalservice"),
        ),
    ]
