# Generated by Django 4.2.7 on 2024-05-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0009_remove_hospitalservice_hospital_hospital_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambulance",
            name="address_bn",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="ambulance",
            name="name_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ambulance",
            name="slug_bn",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="address_bn",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="hospital",
            name="availability_bn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="slug_bn",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="hospitalservice",
            name="service_name_bn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="slug_bn",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="test_name_bn",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="testcatagory",
            name="name_bn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
