# Generated by Django 4.2.7 on 2024-05-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0011_test_delivery_time_bn_test_fee_bn"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="hospital_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="hospital_no_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
