# Generated by Django 4.2.7 on 2024-05-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0012_hospital_hospital_no_hospital_hospital_no_bn"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambulance",
            name="position",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="position",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
