# Generated by Django 4.2.7 on 2024-05-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0013_ambulance_position_hospital_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambulance",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="test",
            name="position",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
