# Generated by Django 4.2.7 on 2024-05-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hospital",
            "0014_ambulance_published_hospital_published_test_position_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="short_description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="short_description_bn",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
