# Generated by Django 4.2.7 on 2024-06-04 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0016_alter_ambulance_location_alter_hospital_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambulance",
            name="profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ambulance",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
