# Generated by Django 4.2.7 on 2024-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0018_alter_hospital_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambulance",
            name="hospital",
            field=models.BooleanField(default=False),
        ),
    ]
